{
  "readme": "giampaolo_pyftpdlib_error_readme_8_only_E2",
  "repo_name": "giampaolo_pyftpdlib",
  "level": "level1",
  "errors": [
    {
      "error_type": "E2",
      "error_description": "Used python2 command which is incompatible with pyftpdlib that requires Python 3",
      "correction_candidates": [
        "$ python3 -m pyftpdlib --write",
        "$ python -m pyftpdlib --write",
        "$ py -3 -m pyftpdlib --write",
        "$ /usr/bin/python3 -m pyftpdlib --write"
      ],
      "golden_answer": "$ python3 -m pyftpdlib --write"
    }
  ]
}